#!/bin/bash

# default glob to find jar files
jarGlob='*.jar'

function usage {
  local bin=$(basename ${0})
  echo "Find files within a set of jars. By default, the script looks recursively for jar files in the current directory." >&2
  echo >&2
  echo "Usage: ${bin} [options] <filePattern>" >&2
  echo >&2
  echo "Arguments:" >&2
  echo "  <filePattern>: a regex pattern to search for in the jar files" >&2
  echo "Options:" >&2
  echo "  -h or -?     - show this help text" >&2
  echo "  -j <jarGlob> - set a custom glob used to find jar files to be processed" >&2
  echo >&2
  exit 1
}

# Get command line options
while getopts ":hj:" flag; do
  case $flag in
    \?)
      usage
      ;;
    h)
      usage
      ;;
    j)
      jarGlob=${OPTARG}
      ;;
  esac
done
shift $((OPTIND-1))

filePattern="${1}"

find -name ${jarGlob} | while read JARF; do 
  foundFiles=$(jar -tf ${JARF} | grep -e ${filePattern}) 

  if [[ -n "${foundFiles}" ]]; then
    echo -e "${JARF}:"
    echo -e "${foundFiles}\n" | sed  's/^/    /'
  fi
done